###read all users
GET http://localhost:4000/user-api/users 

###Read user by ObjectId
GET http://localhost:4000/user-api/users/697d89624198c80cc52e1ce2



###Create user
POST  http://localhost:4000/user-api/users
Content-Type: application/json

{
    "username":"1111",
    "password":"1111",
    "age":19
}

###Update user
PUT  http://localhost:4000/user-api/users/697e0104bc9ceb021a0b0f89
Content-Type: application/json

{
    "username":"Ashu",
    "password":"abc",
    "age":19
}


###Delete user by objId
DELETE http://localhost:4000/user-api/users/697e022c168b22d6b1dc830c


















###CREATING PROUCT API
#PRODUCT obj schema: {pid,productName,price}

###
GET http://localhost:4000/product-api/products

###create product
POST http://localhost:4000/product-api/products

Content-Type: application/json

{
    "pid":1,
    "productName":"laptop",
    "price":999
}



