###CReate USer
POST http://localhost:4000/user-api/users
Content-Type : application/json

{
    "name":"Anusha",
    "email":"Anusha@gmail.com",
    "dateOfBirth":"2005-03-15",
    "mobileNumber":6300
}
###Read all users
GET http://localhost:4000/user-api/users

###read user by id
GET http://localhost:4000/user-api/users/69a69825196d50c467830ecf

###Delete user by id
DELETE  http://localhost:4000/user-api/users/69a6929aebacfc1c651b3ea0


###To activateuser
PATCH http://localhost:4000/user-api/users/69a6929aebacfc1c651b3ea0